version: '2'
services:

  # The Web Server
  teamwork_web:
    build:
      context: ../../
      dockerfile: ./docker/prod/web.prod.dockerfile
    working_dir: /var/www
    ports:
      - 8080:80 #NOTE: to test prod deploy on dev machine, need to change this line from 80:80 to 8080:80
      #- 443:443
    #volumes:
      #- "${LE_DIR}:/etc/letsencrypt"
